### ISSUE TITLE
Run as Daemon / Background Task

### ISSUE THREAD

**Issue by uncenteredDiv** [Siepomaga/mjml-server#1]
Hi,

is there a way to run mjml-server as a Daemon / Background Task?
So that i don't have to keep the CLI open all the time ...

**Comment by uncenteredDiv** [comment]
Got it - just use:

`mjml-server &>/dev/null &`

**Comment by florentdestremau** [comment]
you can use something like http://pm2.keymetrics.io/ as well

`pm2 start mjml-server`
